### ISSUE TITLE
web pull 失败

### ISSUE THREAD

**Issue by czy12366** [en0th/ElectricRat#27]
![image](https://github.com/user-attachments/assets/4d3b423e-b3c4-42f0-9e0f-688e554eb140)
web pull失败，网络没问题

**Comment by en0th** [comment]
我找到问题所在了，我直接将docker-compose.yml的version字段删除就不会有这样的WARN了。应该是觉得这个字段存在confusion吧。

docker pull 不行的话，你需要设置docker代理，可以参考官方的做法：
[systemd unit file](https://docs.docker.com/config/daemon/proxy/#systemd-unit-file)
我不建议使用Daemon configuration的方法，更加建议通过systemd unit file设置代理。
